packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: false
publicHoistPattern:
  - "oxlint"
  - "oxlint-tsgolint"
minimumReleaseAge: 4320 # time in minutes, equals 72 hours
saveExact: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
