packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": 24.13.3
  "@vitest/coverage-v8": 4.1.10
  dotenv: 17.4.2
  oxlint: 1.74.0
  oxlint-tsgolint: 7.0.2001
  vitest: 4.1.10

allowBuilds:
  esbuild: false
publicHoistPattern:
  - "oxlint"
  - "oxlint-tsgolint"
minimumReleaseAge: 4320 # time in minutes, equals 72 hours
saveExact: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver@6.3.1"
patchedDependencies:
  png-js: patches/png-js.patch
