/**
 * @module points-of-attack.types - Defines the points of attack.
 */

export enum POINTS_OF_ATTACK {
    USER_INTERFACE = "USER_INTERFACE",
    PROCESSING_INFRASTRUCTURE = "PROCESSING_INFRASTRUCTURE",
    DATA_STORAGE_INFRASTRUCTURE = "DATA_STORAGE_INFRASTRUCTURE",
    COMMUNICATION_INFRASTRUCTURE = "COMMUNICATION_INFRASTRUCTURE",
    COMMUNICATION_INTERFACES = "COMMUNICATION_INTERFACES",
    USER_BEHAVIOUR = "USER_BEHAVIOUR",
}
