{{/*
Validate Database name
*/}}
{{- if .Values.postgresql.enabled }}
{{- if ne .Values.database.name .Values.postgresql.auth.database }}
{{- fail "database.name must match postgresql.auth.database when postgresql.enabled=true" }}
{{- end }}
{{- end }}
