import { SvgIcon, type SvgIconProps } from "@mui/material";
import { createElement } from "react";
import { useMuiIconDefinition } from "#application/hooks/use-mui-icons.hook.ts";

export interface DynamicMuiIconProps extends SvgIconProps {
    iconName: string;
}

/**
 * Renders any MUI icon by name from generated SVG path data instead of the
 * ~4 MB of per-icon components in @mui/icons-material.
 * Renders nothing while the icon data loads or when the name is unknown.
 */
export const DynamicMuiIcon = ({ iconName, ...svgIconProps }: DynamicMuiIconProps) => {
    const definition = useMuiIconDefinition(iconName);

    if (!definition) {
        return null;
    }
    return (
        // Same data-testid convention as the components generated by @mui/icons-material.
        <SvgIcon data-testid={`${iconName}Icon`} {...svgIconProps}>
            {typeof definition === "string" ? (
                <path d={definition} />
            ) : (
                definition.map(([tagName, attributes], elementIndex) =>
                    createElement(tagName, { key: elementIndex, ...attributes })
                )
            )}
        </SvgIcon>
    );
};
