CREATE TYPE "public"."attacker" AS ENUM('ADMINISTRATORS', 'APPLICATION_USERS', 'SYSTEM_USERS', 'UNAUTHORISED_PARTIES');
CREATE TYPE "public"."confidentiality_level" AS ENUM('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'HIGHLY_CONFIDENTIAL');
CREATE TYPE "public"."point_of_attack" AS ENUM('COMMUNICATION_INFRASTRUCTURE', 'COMMUNICATION_INTERFACES', 'DATA_STORAGE_INFRASTRUCTURE', 'PROCESSING_INFRASTRUCTURE', 'USER_BEHAVIOUR', 'USER_INTERFACE');
CREATE TABLE "assets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"confidentiality" integer NOT NULL,
	"integrity" integer NOT NULL,
	"availability" integer NOT NULL,
	"confidentialityJustification" text NOT NULL,
	"integrityJustification" text NOT NULL,
	"availabilityJustification" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"projectId" integer NOT NULL,
	CONSTRAINT "assets_name_not_empty" CHECK ("assets"."name" <> ''),
	CONSTRAINT "assets_confidentiality_min_max" CHECK ("assets"."confidentiality" between 1 and 5),
	CONSTRAINT "assets_integrity_min_max" CHECK ("assets"."integrity" between 1 and 5),
	CONSTRAINT "assets_availability_min_max" CHECK ("assets"."availability" between 1 and 5)
);

CREATE TABLE "catalog_measures" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "catalog_measures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"pointOfAttack" "point_of_attack" NOT NULL,
	"attacker" "attacker" NOT NULL,
	"probability" integer,
	"confidentiality" boolean NOT NULL,
	"integrity" boolean NOT NULL,
	"availability" boolean NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"catalogId" integer NOT NULL,
	CONSTRAINT "catalog_measures_probability_min_max" CHECK ("catalog_measures"."probability" between 1 and 5)
);

CREATE TABLE "catalog_threats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "catalog_threats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"pointOfAttack" "point_of_attack" NOT NULL,
	"attacker" "attacker" NOT NULL,
	"probability" integer NOT NULL,
	"confidentiality" boolean NOT NULL,
	"integrity" boolean NOT NULL,
	"availability" boolean NOT NULL,
	"isDefault" boolean DEFAULT true,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"catalogId" integer NOT NULL,
	CONSTRAINT "catalog_threats_probability_min_max" CHECK ("catalog_threats"."probability" between 1 and 5)
);

CREATE TABLE "catalogs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "catalogs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"language" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "catalogs_name_not_empty" CHECK ("catalogs"."name" <> '')
);

CREATE TABLE "component_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "component_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"pointsOfAttack" "point_of_attack"[] NOT NULL,
	"symbol" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"projectId" integer
);

CREATE TABLE "measure_impacts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "measure_impacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text,
	"setsOutOfScope" boolean NOT NULL,
	"impactsProbability" boolean NOT NULL,
	"impactsDamage" boolean NOT NULL,
	"probability" integer,
	"damage" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"threatId" integer NOT NULL,
	"measureId" integer NOT NULL,
	CONSTRAINT "measure_impacts_measure_id_threat_id_unique" UNIQUE("measureId","threatId"),
	CONSTRAINT "measure_impacts_probability_min_max" CHECK ("measure_impacts"."probability" between 1 and 5),
	CONSTRAINT "measure_impacts_probability" CHECK ("measure_impacts"."impactsProbability" = false OR "measure_impacts"."probability" IS NOT NULL),
	CONSTRAINT "measure_impacts_damage_min_max" CHECK ("measure_impacts"."damage" between 1 and 5),
	CONSTRAINT "measure_impacts_damage" CHECK ("measure_impacts"."impactsDamage" = false OR "measure_impacts"."damage" IS NOT NULL)
);

CREATE TABLE "measures" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "measures_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"scheduledAt" timestamp with time zone NOT NULL,
	"catalogMeasureId" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"projectId" integer NOT NULL,
	CONSTRAINT "measures_name_not_empty" CHECK ("measures"."name" <> '')
);

CREATE TABLE "projects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"confidentialityLevel" "confidentiality_level" DEFAULT 'INTERNAL' NOT NULL,
	"lineOfToleranceGreen" integer DEFAULT 6,
	"lineOfToleranceRed" integer DEFAULT 15,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"catalogId" integer NOT NULL,
	CONSTRAINT "projects_name_not_empty" CHECK ("projects"."name" <> '')
);

CREATE TABLE "systems" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "systems_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"data" jsonb,
	"image" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"projectId" integer NOT NULL,
	CONSTRAINT "project_id" UNIQUE("projectId")
);

CREATE TABLE "threats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "threats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pointOfAttackId" varchar(21) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"pointOfAttack" "point_of_attack" NOT NULL,
	"attacker" "attacker" NOT NULL,
	"probability" integer NOT NULL,
	"confidentiality" boolean NOT NULL,
	"integrity" boolean NOT NULL,
	"availability" boolean NOT NULL,
	"doneEditing" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"catalogThreatId" integer NOT NULL,
	"projectId" integer NOT NULL,
	CONSTRAINT "threats_name_not_empty" CHECK ("threats"."name" <> ''),
	CONSTRAINT "threats_probability_min_max" CHECK ("threats"."probability" between 1 and 5)
);

CREATE TABLE "tokens" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tokens_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"token" varchar(500) NOT NULL,
	"expiresAt" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firstname" varchar(255) NOT NULL,
	"lastname" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "users_catalogs" (
	"role" smallint NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"userId" integer NOT NULL,
	"catalogId" integer NOT NULL
);

CREATE TABLE "users_projects" (
	"role" smallint NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"userId" integer NOT NULL,
	"projectId" integer NOT NULL
);

ALTER TABLE "assets" ADD CONSTRAINT "assets_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "catalog_measures" ADD CONSTRAINT "catalog_measures_catalogId_catalogs_id_fk" FOREIGN KEY ("catalogId") REFERENCES "public"."catalogs"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "catalog_threats" ADD CONSTRAINT "catalog_threats_catalogId_catalogs_id_fk" FOREIGN KEY ("catalogId") REFERENCES "public"."catalogs"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "component_types" ADD CONSTRAINT "component_types_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "measure_impacts" ADD CONSTRAINT "measure_impacts_threatId_threats_id_fk" FOREIGN KEY ("threatId") REFERENCES "public"."threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "measure_impacts" ADD CONSTRAINT "measure_impacts_measureId_measures_id_fk" FOREIGN KEY ("measureId") REFERENCES "public"."measures"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "measures" ADD CONSTRAINT "measures_catalogMeasureId_catalog_measures_id_fk" FOREIGN KEY ("catalogMeasureId") REFERENCES "public"."catalog_measures"("id") ON DELETE set null ON UPDATE cascade;
ALTER TABLE "measures" ADD CONSTRAINT "measures_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "projects" ADD CONSTRAINT "projects_catalogId_catalogs_id_fk" FOREIGN KEY ("catalogId") REFERENCES "public"."catalogs"("id") ON DELETE no action ON UPDATE cascade;
ALTER TABLE "systems" ADD CONSTRAINT "systems_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "threats" ADD CONSTRAINT "threats_catalogThreatId_catalog_threats_id_fk" FOREIGN KEY ("catalogThreatId") REFERENCES "public"."catalog_threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "threats" ADD CONSTRAINT "threats_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "users_catalogs" ADD CONSTRAINT "users_catalogs_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "users_catalogs" ADD CONSTRAINT "users_catalogs_catalogId_catalogs_id_fk" FOREIGN KEY ("catalogId") REFERENCES "public"."catalogs"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "users_projects" ADD CONSTRAINT "users_projects_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "users_projects" ADD CONSTRAINT "users_projects_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
CREATE INDEX "assets_project_id" ON "assets" USING btree ("projectId");
CREATE INDEX "assets_name" ON "assets" USING btree ("name");
CREATE INDEX "catalog_measures_catalog_id" ON "catalog_measures" USING btree ("catalogId");
CREATE INDEX "catalog_measures_name" ON "catalog_measures" USING btree ("name");
CREATE INDEX "catalog_measures_point_of_attack" ON "catalog_measures" USING btree ("pointOfAttack");
CREATE INDEX "catalog_measures_attacker" ON "catalog_measures" USING btree ("attacker");
CREATE INDEX "catalog_threats_catalog_id" ON "catalog_threats" USING btree ("catalogId");
CREATE INDEX "catalog_threats_name" ON "catalog_threats" USING btree ("name");
CREATE INDEX "catalog_threats_point_of_attack" ON "catalog_threats" USING btree ("pointOfAttack");
CREATE INDEX "catalog_threats_attacker" ON "catalog_threats" USING btree ("attacker");
CREATE INDEX "catalogs_name" ON "catalogs" USING btree ("name");
CREATE INDEX "component_types_project_id" ON "component_types" USING btree ("projectId");
CREATE INDEX "measure_impacts_measure_id_threat_id" ON "measure_impacts" USING btree ("measureId","threatId");
CREATE INDEX "measures_catalog_measure_id" ON "measures" USING btree ("catalogMeasureId");
CREATE INDEX "measures_project_id" ON "measures" USING btree ("projectId");
CREATE INDEX "projects_catalog_id" ON "projects" USING btree ("catalogId");
CREATE INDEX "projects_name" ON "projects" USING btree ("name");
CREATE INDEX "threats_catalog_threat_id" ON "threats" USING btree ("catalogThreatId");
CREATE INDEX "threats_project_id" ON "threats" USING btree ("projectId");
CREATE INDEX "tokens_token" ON "tokens" USING btree ("token");
CREATE INDEX "users_email" ON "users" USING btree ("email");
CREATE INDEX "users_catalogs_catalog_id" ON "users_catalogs" USING btree ("catalogId");
CREATE UNIQUE INDEX "users_catalogs_user_id_catalog_id" ON "users_catalogs" USING btree ("userId","catalogId");
CREATE INDEX "users_projects_project_id" ON "users_projects" USING btree ("projectId");
CREATE UNIQUE INDEX "users_projects_user_id_project_id" ON "users_projects" USING btree ("userId","projectId");