CREATE TABLE "child_threats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "child_threats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pointOfAttackId" varchar(21) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"pointOfAttack" "point_of_attack" NOT NULL,
	"attacker" "attacker" NOT NULL,
	"probability" integer NOT NULL,
	"confidentiality" boolean NOT NULL,
	"integrity" boolean NOT NULL,
	"availability" boolean NOT NULL,
	"doneEditing" boolean NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"genericThreatId" integer NOT NULL,
	"projectId" integer NOT NULL,
	CONSTRAINT "child_threats_name_not_empty" CHECK ("child_threats"."name" <> ''),
	CONSTRAINT "child_threats_probability_min_max" CHECK ("child_threats"."probability" between 1 and 5)
);

CREATE TABLE "generic_threats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generic_threats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pointOfAttackId" varchar(21) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"pointOfAttack" "point_of_attack" NOT NULL,
	"attacker" "attacker" NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"catalogThreatId" integer NOT NULL,
	"projectId" integer NOT NULL,
	CONSTRAINT "generic_threats_name_not_empty" CHECK ("generic_threats"."name" <> '')
);

ALTER TABLE "child_threats" ADD CONSTRAINT "child_threats_genericThreatId_generic_threats_id_fk" FOREIGN KEY ("genericThreatId") REFERENCES "public"."generic_threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "child_threats" ADD CONSTRAINT "child_threats_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "generic_threats" ADD CONSTRAINT "generic_threats_catalogThreatId_catalog_threats_id_fk" FOREIGN KEY ("catalogThreatId") REFERENCES "public"."catalog_threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "generic_threats" ADD CONSTRAINT "generic_threats_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
CREATE INDEX "child_threats_generic_threat_id" ON "child_threats" USING btree ("genericThreatId");
CREATE INDEX "child_threats_project_id" ON "child_threats" USING btree ("projectId");
CREATE INDEX "generic_threats_catalog_threat_id" ON "generic_threats" USING btree ("catalogThreatId");
CREATE INDEX "generic_threats_project_id" ON "generic_threats" USING btree ("projectId");