CREATE TABLE "child_threat_measure_impacts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "child_threat_measure_impacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"setsOutOfScope" boolean NOT NULL,
	"impactsProbability" boolean NOT NULL,
	"impactsDamage" boolean NOT NULL,
	"probability" integer,
	"damage" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"childThreatId" integer NOT NULL,
	"measureId" integer NOT NULL,
	CONSTRAINT "child_threat_measure_impacts_measure_id_child_threat_id_unique" UNIQUE("measureId","childThreatId"),
	CONSTRAINT "child_threat_measure_impacts_probability_min_max" CHECK ("child_threat_measure_impacts"."probability" between 1 and 5),
	CONSTRAINT "child_threat_measure_impacts_probability" CHECK ("child_threat_measure_impacts"."impactsProbability" = false OR "child_threat_measure_impacts"."probability" IS NOT NULL),
	CONSTRAINT "child_threat_measure_impacts_damage_min_max" CHECK ("child_threat_measure_impacts"."damage" between 1 and 5),
	CONSTRAINT "child_threat_measure_impacts_damage" CHECK ("child_threat_measure_impacts"."impactsDamage" = false OR "child_threat_measure_impacts"."damage" IS NOT NULL)
);

ALTER TABLE "child_threat_measure_impacts" ADD CONSTRAINT "child_threat_measure_impacts_childThreatId_child_threats_id_fk" FOREIGN KEY ("childThreatId") REFERENCES "public"."child_threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "child_threat_measure_impacts" ADD CONSTRAINT "child_threat_measure_impacts_measureId_measures_id_fk" FOREIGN KEY ("measureId") REFERENCES "public"."measures"("id") ON DELETE cascade ON UPDATE cascade;
CREATE INDEX "child_threat_measure_impacts_measure_id_child_threat_id" ON "child_threat_measure_impacts" USING btree ("measureId","childThreatId");
CREATE INDEX "child_threat_measure_impacts_child_threat_id" ON "child_threat_measure_impacts" USING btree ("childThreatId");
CREATE INDEX "child_threat_measure_impacts_measure_id" ON "child_threat_measure_impacts" USING btree ("measureId");