CREATE TYPE "public"."threat_status" AS ENUM('new', 'in progress', 'finalized', 'out of scope');

-- Copy the old flat threats aside (bare data copy, no constraints/sequence) and drop the original
-- so the new refined table can claim the "threats" name and its threats_* object names.
CREATE TABLE "_legacy_threats" AS TABLE "threats";

ALTER TABLE "measure_impacts" DROP CONSTRAINT "measure_impacts_threatId_threats_id_fk";
ALTER TABLE "measure_impacts" DROP CONSTRAINT "measure_impacts_measure_id_threat_id_unique";
DROP INDEX IF EXISTS "measure_impacts_measure_id_threat_id";

DROP TABLE "threats";

CREATE TABLE "generic_threats" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generic_threats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "pointOfAttackId" varchar(21) NOT NULL,
    "name" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "pointOfAttack" "point_of_attack" NOT NULL,
    "attacker" "attacker" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "catalogThreatId" integer NOT NULL,
    "projectId" integer NOT NULL,
    CONSTRAINT "generic_threats_name_not_empty" CHECK ("generic_threats"."name" <> '')
);

CREATE TABLE "threats" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "threats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "pointOfAttackId" varchar(21) NOT NULL,
    "name" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "pointOfAttack" "point_of_attack" NOT NULL,
    "attacker" "attacker" NOT NULL,
    "probability" integer NOT NULL,
    "confidentiality" boolean NOT NULL,
    "integrity" boolean NOT NULL,
    "availability" boolean NOT NULL,
    "status" "public"."threat_status" NOT NULL DEFAULT 'new'::"public"."threat_status",
    "createdAt" timestamp with time zone DEFAULT now() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "genericThreatId" integer NOT NULL,
    "projectId" integer NOT NULL,
    "_old_threat_id" integer,
    CONSTRAINT "threats_name_not_empty" CHECK ("threats"."name" <> ''),
    CONSTRAINT "threats_probability_min_max" CHECK ("threats"."probability" between 1 and 5)
);

INSERT INTO "generic_threats" ("pointOfAttackId", "name", "description", "pointOfAttack", "attacker", "createdAt", "updatedAt", "catalogThreatId", "projectId")
SELECT
    t."pointOfAttackId",
    ct."name",
    COALESCE(ct."description", ''),
    ct."pointOfAttack",
    ct."attacker",
    MIN(t."createdAt") AS "createdAt",
    MAX(t."updatedAt") AS "updatedAt",
    t."catalogThreatId",
    t."projectId"
FROM "_legacy_threats" t
JOIN "catalog_threats" ct ON ct."id" = t."catalogThreatId"
GROUP BY
    t."catalogThreatId",
    t."projectId",
    t."pointOfAttackId",
    ct."name",
    ct."description",
    ct."pointOfAttack",
    ct."attacker";

INSERT INTO "threats" ("pointOfAttackId", "name", "description", "pointOfAttack", "attacker", "probability", "confidentiality", "integrity", "availability", "status", "createdAt", "updatedAt", "genericThreatId", "projectId", "_old_threat_id")
SELECT
    t."pointOfAttackId",
    t."name",
    COALESCE(t."description", ''),
    t."pointOfAttack",
    t."attacker",
    t."probability",
    t."confidentiality",
    t."integrity",
    t."availability",
    CASE
        WHEN t."doneEditing" = true THEN 'finalized'::"public"."threat_status"
        ELSE 'new'::"public"."threat_status"
    END,
    t."createdAt",
    t."updatedAt",
    gt."id",
    t."projectId",
    t."id"
FROM "_legacy_threats" t
JOIN "generic_threats" gt
    ON gt."catalogThreatId" = t."catalogThreatId"
    AND gt."projectId" = t."projectId"
    AND gt."pointOfAttackId" = t."pointOfAttackId";

-- measure_impacts."threatId" already exists (it pointed at the legacy threats);
-- remap it onto the new refined threats ids.
UPDATE "measure_impacts" mi
SET "threatId" = t."id"
FROM "threats" t
WHERE t."_old_threat_id" = mi."threatId";

ALTER TABLE "measure_impacts"
    ADD CONSTRAINT "measure_impacts_threatId_threats_id_fk"
    FOREIGN KEY ("threatId") REFERENCES "public"."threats"("id") ON DELETE cascade ON UPDATE cascade;

ALTER TABLE "measure_impacts"
    ADD CONSTRAINT "measure_impacts_measure_id_threat_id_unique"
    UNIQUE("measureId", "threatId");

CREATE INDEX "measure_impacts_measure_id_threat_id" ON "measure_impacts" USING btree ("measureId", "threatId");
CREATE INDEX "measure_impacts_threat_id" ON "measure_impacts" USING btree ("threatId");
CREATE INDEX "measure_impacts_measure_id" ON "measure_impacts" USING btree ("measureId");

ALTER TABLE "threats" DROP COLUMN "_old_threat_id";

DROP TABLE "_legacy_threats";

ALTER TABLE "generic_threats" ADD CONSTRAINT "generic_threats_catalogThreatId_catalog_threats_id_fk" FOREIGN KEY ("catalogThreatId") REFERENCES "public"."catalog_threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "generic_threats" ADD CONSTRAINT "generic_threats_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "threats" ADD CONSTRAINT "threats_genericThreatId_generic_threats_id_fk" FOREIGN KEY ("genericThreatId") REFERENCES "public"."generic_threats"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "threats" ADD CONSTRAINT "threats_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE cascade;

CREATE INDEX "generic_threats_catalog_threat_id" ON "generic_threats" USING btree ("catalogThreatId");
CREATE INDEX "generic_threats_project_id" ON "generic_threats" USING btree ("projectId");
CREATE INDEX "threats_generic_threat_id" ON "threats" USING btree ("genericThreatId");
CREATE INDEX "threats_project_id" ON "threats" USING btree ("projectId");
