CREATE TABLE "folders" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "folders_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"parentId" integer,
	"userId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "folders_name_not_empty" CHECK ("folders"."name" <> '')
);

ALTER TABLE "users_projects" ADD COLUMN "folderId" integer;
ALTER TABLE "folders" ADD CONSTRAINT "folders_parentId_folders_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."folders"("id") ON DELETE cascade ON UPDATE cascade;
ALTER TABLE "folders" ADD CONSTRAINT "folders_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
CREATE INDEX "folders_user_id" ON "folders" USING btree ("userId");
CREATE INDEX "folders_parent_id" ON "folders" USING btree ("parentId");
ALTER TABLE "users_projects" ADD CONSTRAINT "users_projects_folderId_folders_id_fk" FOREIGN KEY ("folderId") REFERENCES "public"."folders"("id") ON DELETE set null ON UPDATE cascade;
CREATE INDEX "users_projects_folder_id" ON "users_projects" USING btree ("folderId");