/**
 * @module points-of-attack.types Defines constants for the points of attacks.
 */

export enum POINTS_OF_ATTACK {
    COMMUNICATION_INFRASTRUCTURE = "COMMUNICATION_INFRASTRUCTURE",
    COMMUNICATION_INTERFACES = "COMMUNICATION_INTERFACES",
    DATA_STORAGE_INFRASTRUCTURE = "DATA_STORAGE_INFRASTRUCTURE",
    PROCESSING_INFRASTRUCTURE = "PROCESSING_INFRASTRUCTURE",
    USER_BEHAVIOR = "USER_BEHAVIOUR",
    USER_INTERFACE = "USER_INTERFACE",
}
