name: CI

on:
  push:
    branches:
      - main
      - next
      - "v[0-9]+.[0-9]+.x"
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"

env:
  TURBO_TELEMETRY_DISABLED: 1
  NODE_ENV: production

jobs:
  lint:
    name: Lint and Format Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Repository
        uses: ./.github/actions/repository-setup
      - name: Run format check
        run: pnpm format:check
      - name: Run lint
        run: pnpm lint

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
      - name: Setup Repository
        uses: ./.github/actions/repository-setup
      - name: Build backend
        run: pnpm build --filter="..../apps/backend"
      - name: Upload backend build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: backend-dist
          path: apps/backend/dist/

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
      - name: Setup Repository
        uses: ./.github/actions/repository-setup
      - name: Build Frontend
        run: pnpm build --filter="..../apps/frontend"
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: frontend-build
          path: apps/frontend/build/

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build-backend
    services:
      postgres:
        image: postgres:18.3-alpine
        env:
          POSTGRES_DB: threatsea
          POSTGRES_USER: user
          POSTGRES_PASSWORD: user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      NODE_ENV: development
      JWT_SECRET: test-secret
      EXPRESS_SESSION_SECRET: test-session-secret
      AUTH_METHOD: fixed
      ORIGIN_APP: http://localhost:3000
      ORIGIN_BACKEND: http://localhost:8000
      DATABASE_USER: user
      DATABASE_PASSWORD: user
      DATABASE_NAME: threatsea
      DATABASE_HOST: localhost
      DATABASE_TLS: disabled
      COOKIES_SECURE_OPTION: disabled
      LOG_LEVEL: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
      - name: Setup Repository
        uses: ./.github/actions/repository-setup
      - name: Test backend
        run: pnpm -r --filter="..../apps/backend" test:ci
      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: backend-test-results
          path: |
            apps/backend/junit.xml
            apps/backend/coverage/

  test-frontend:
    name: Test Frontend (Component Tests)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build-frontend
    env:
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
      - name: Setup Repository
        uses: ./.github/actions/repository-setup
      - name: Run component tests
        run: pnpm --filter="..../apps/frontend" test:unit:ci
      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: always()
        with:
          name: frontend-test-results
          path: |
            apps/frontend/junit.xml
            apps/frontend/coverage/

  build-container-image:
    name: Build Container Image
    runs-on: ubuntu-latest
    if: (github.ref_name != 'main' && github.ref_name != 'next') || github.ref_type != 'branch'
    permissions:
      contents: read
    needs:
      - test-backend
      - test-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          lfs: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - uses: rlespinasse/github-slug-action@e6f261660910b273384c5c42b17a0217881b217a # v5
      - name: Build Container Image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ github.repository_owner }}/threatsea:${{ env.GITHUB_REF_SLUG }}

  release:
    name: Create and push Release
    if: github.repository_owner == 'MaibornWolff' && github.ref_type == 'branch' && github.ref_name == 'main'
    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write # for Sigstore-based provenance signing
      issues: write
      packages: write
    needs:
      - test-backend
      - test-frontend
    uses: ./.github/workflows/release.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SO_API_TOKEN: ${{ secrets.SO_API_TOKEN }}
